#INCLUDE <16F877A.h>
#USE DELAY (CLOCK=4000000) //4MHz Clock
#FUSES XT, NOPROTECT, NOWDT, NOBROWNOUT, PUT, NOLVP
#BYTE PORTD=8
#BYTE PORTA=5
#BYTE PORTB=6
Byte CONST display[10]= {0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x67};
#DEFINE TUNI PORTD,7
#DEFINE TDEC PORTD,3
INT CONT;

LONG CONCRET;
VOID MOSTRAR()
{
INT UNI,DEC;

DEC = CONT/10;
UNI=CONT%10;
PORTB=(DISPLAY[UNI]);

BIT_CLEAR(TDEC);
BIT_SET(TUNI);
DELAY_MS(1);
PORTB=(DISPLAY[DEC]);

BIT_CLEAR(TUNI);
BIT_SET(TDEC);
DELAY_MS(1);
}

VOID RET1SEG()
{
CONTRET=500;
WHILE (CONTRET>0)
{
MOSTRAR();
